apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: phrases

images:
- name: backend
  newName: backend
  newTag: v1

resources:
- deployment.yaml
- service.yaml
- httproute.yaml